name: the_guy
description: "The Guy - Service Provider App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # UI
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  flutter_screenutil: ^5.9.0
  lottie: ^3.3.3
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod: ^2.5.1
  state_notifier: ^1.0.0
  
  # Navigation
  go_router: ^17.2.2
  
  # Networking
  dio: ^5.3.2
  socket_io_client: ^3.1.4
  stomp_dart_client: ^3.0.1
  
  # Storage
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.2.2
  
  # Location
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  
  # Media
  image_picker: ^1.0.4
  permission_handler: ^12.0.1
  audioplayers: ^6.6.0
  
  # Charts & Utilities
  fl_chart: ^1.2.0
  intl: ^0.20.2
  equatable: ^2.0.5
  
  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/noise.png
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/sounds/
    - assets/providers/

